[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://student-revision-app-server.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
